### ISSUE TITLE
docker-compose.yml should be for flare instead of blaze

### ISSUE THREAD

**Issue by haemka** [medizininformatik-initiative/flare#184]
The `docker-compose.yml` in this project should rather contain a configuration for running flare instead of a blaze test server. The documentation should refer to official blaze documentation on how to set up blaze.

Containing a `docker-compose.yml` and a `Dockerfile` for generally different purposes is just confusing.

**Comment by alexanderkiel** [comment]
The `docker-compose.yml` is used for development of FLARE, were one needs a Blaze server to be able to start FLARE. In which use case do you check out the FLARE repo? Development in FLARE or deployment of a system using FLARE?

**Comment by haemka** [comment]
I don't need a Blaze for running FLARE. Regardless of development or deployment. I can use whatever FHIR server I want to use. Of course setting up FLARE for development purposes might be a good choice, but as I mentioned putting a `Dockerfile` and a `docker-compose.yml` with generally different purposes in a repository is at least confusing.

**Comment by alexanderkiel** [comment]
Ok you are right, I'll fix that.
