### ISSUE TITLE
use recorded-date by timerestriction

### ISSUE THREAD

**Issue by KutSaleh** [medizininformatik-initiative/flare#188]
If we use the timerestriction when querying for diagnoses in a cohort, then the onset-date is used, would it be possible to use the recorded-date in addition as well?

**Comment by juliangruendner** [comment]
@KutSaleh additionally is difficult - its still an ongoing discussion which field should be used. In this case its meant to be the clinical date and for most fhir resources this is defined, see: https://hl7.org/fhir/R4/searchparameter-registry.html (search for clinical-date).
Condition is the one exception and there is no clear agreement on what the clinical data should be.
@julsas  - is there a definitiv answer to this now?

**Comment by KutSaleh** [comment]
thank you for your quick reply. I would prefer the recodedDate as this is with 1..1 cardinality in the diagnosis MII module, see https://simplifier.net/mii-basismodul-diagnose-2024/mii_pr_diagnose_condition as well it is listed as a search parameter (recoded-date)

**Comment by DannyAmmon** [comment]
Please keep in mind that Condition.onsetDateTime does not exist in structured form in most primary documentation systems.

**Comment by KutSaleh** [comment]
is there anything new?

**Comment by julsas** [comment]
No final answer but I don't mind switching back to recordedDate.

Condition.onset was chosen because we assumed researchers would be most interested in onset and less interested on recordedDate. Downside is that onset is optional in our profile because most primary systems won't have it present.
Condition.recordedDate will deliver more results as primary systems will have it and it is mandatory in our diagnosis profile.

**Comment by KutSaleh** [comment]
Thanx,  can it then be changed to recordedDate? or should the final answer be given first? If so, who can give the final answer?

**Comment by julsas** [comment]
Yes, it will be changed to recordedDate.

**Comment by KutSaleh** [comment]
@juliangruendner

**Comment by juliangruendner** [comment]
@KutSaleh  - we will change it for the next release then -

**Comment by KutSaleh** [comment]
thx
